---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "unarchiving files of backend"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "installing dependencies of node"
  shell: |
    cd ~/backend-app
    npm i

- name: "checking node app and executing it with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu